#WEEK 3 CODE

In [304]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [305]:
housing = pd.read_csv("CRMLS_Residential_SingleFamily_202505_202605.csv")

In [306]:
housing.drop(columns=["LogLotSize","LogClosePrice"],inplace=True)

In [307]:
missing = housing.isnull().sum()
print("missing:\n",missing)

print("\nduplicates:")
dupes = housing["ListingKey"].duplicated().sum()
print(dupes)

missing:
 BuyerAgentAOR                     3677
ListAgentAOR                        31
Flooring                         50545
ViewYN                           12901
WaterfrontYN                    141924
                                 ...
PostalCode                           2
AssociationFee                   41364
LotSizeSquareFeet                 2433
MiddleOrJuniorSchoolDistrict    141997
DataMonth                            0
Length: 79, dtype: int64

duplicates:
105

Make new data frames using a copy of housing

In [308]:
housing_drop = housing.copy()
housing_median = housing.copy()
housing_feature = housing.copy()

1. Dropping all missing and duplicate values

In [309]:
housing_drop = housing_drop.drop_duplicates(subset="ListingKey")
housing_drop = housing_drop.dropna()

In [310]:
missing = housing_drop.isnull().sum()
print("missing:\n",missing)

print("\nduplicates:")
dupes = housing_drop["ListingKey"].duplicated().sum()
print(dupes)

print(f"Rows kept: {len(housing_drop)/len(housing)*100:.2f}%")

missing:
 BuyerAgentAOR                   0
ListAgentAOR                    0
Flooring                        0
ViewYN                          0
WaterfrontYN                    0
                               ..
PostalCode                      0
AssociationFee                  0
LotSizeSquareFeet               0
MiddleOrJuniorSchoolDistrict    0
DataMonth                       0
Length: 79, dtype: int64

duplicates:
0
Rows kept: 0.00%

2. Using median and mode

In [311]:
housing_median = housing_median.drop_duplicates(subset="ListingKey")

num_cols = housing_median.select_dtypes(include=np.number).columns
catg_cols = housing_median.select_dtypes(include="object").columns

housing_median[num_cols] = housing_median[num_cols].fillna(housing_median[num_cols].median())

for col in catg_cols:
    housing_median[col] = housing_median[col].fillna(housing_median[col].mode()[0])

/tmp/ipykernel_3709/1949011766.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  housing_median[col] = housing_median[col].fillna(housing_median[col].mode()[0])

In [312]:
missing = housing_median.isnull().sum()
print("missing:\n",missing)

print("\nduplicates:")
dupes = housing_median["ListingKey"].duplicated().sum()
print(dupes)

print(f"Rows kept: {len(housing_median)/len(housing)*100:.2f}%")

missing:
 BuyerAgentAOR                        0
ListAgentAOR                         0
Flooring                             0
ViewYN                               0
WaterfrontYN                         0
                                 ...
PostalCode                           0
AssociationFee                       0
LotSizeSquareFeet                    0
MiddleOrJuniorSchoolDistrict    141892
DataMonth                            0
Length: 79, dtype: int64

duplicates:
0
Rows kept: 99.93%

3. More specific to feautures

In [313]:
housing.columns.sort_values()

Index(['AboveGradeFinishedArea', 'AssociationFee', 'AssociationFeeFrequency',
       'AttachedGarageYN', 'BasementYN', 'BathroomsTotalInteger',
       'BedroomsTotal', 'BelowGradeFinishedArea', 'BuilderName',
       'BuildingAreaTotal', 'BusinessType', 'BuyerAgentAOR',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'BuyerAgentMlsId',
       'BuyerOfficeAOR', 'BuyerOfficeName', 'City', 'CloseDate', 'ClosePrice',
       'CoBuyerAgentFirstName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'CoListOfficeName', 'ContractStatusChangeDate', 'CountyOrParish',
       'CoveredSpaces', 'DataMonth', 'DaysOnMarket', 'ElementarySchool',
       'ElementarySchoolDistrict', 'FireplaceYN', 'FireplacesTotal',
       'Flooring', 'GarageSpaces', 'HighSchool', 'HighSchoolDistrict',
       'Latitude', 'Levels', 'ListAgentAOR', 'ListAgentEmail',
       'ListAgentFirstName', 'ListAgentFullName', 'ListAgentLastName',
       'ListOfficeName', 'ListPrice', 'ListingContractDate', 'ListingId',
       'ListingKey', 'ListingKeyNumeric', 'LivingArea', 'Longitude',
       'LotSizeAcres', 'LotSizeArea', 'LotSizeDimensions', 'LotSizeSquareFeet',
       'MLSAreaMajor', 'MainLevelBedrooms', 'MiddleOrJuniorSchool',
       'MiddleOrJuniorSchoolDistrict', 'MlsStatus', 'NewConstructionYN',
       'OriginalListPrice', 'ParkingTotal', 'PoolPrivateYN', 'PostalCode',
       'PropertySubType', 'PropertyType', 'PurchaseContractDate',
       'StateOrProvince', 'Stories', 'StreetNumberNumeric', 'SubdivisionName',
       'TaxAnnualAmount', 'TaxYear', 'UnparsedAddress', 'ViewYN',
       'WaterfrontYN', 'YearBuilt'],
      dtype='object')

In [314]:
for col in housing.columns.sort_values():
    print(f"{col}: {housing[col].dtype}")

AboveGradeFinishedArea: float64
AssociationFee: float64
AssociationFeeFrequency: object
AttachedGarageYN: object
BasementYN: object
BathroomsTotalInteger: float64
BedroomsTotal: float64
BelowGradeFinishedArea: float64
BuilderName: object
BuildingAreaTotal: float64
BusinessType: float64
BuyerAgentAOR: object
BuyerAgentFirstName: object
BuyerAgentLastName: object
BuyerAgentMlsId: object
BuyerOfficeAOR: object
BuyerOfficeName: object
City: object
CloseDate: object
ClosePrice: float64
CoBuyerAgentFirstName: object
CoListAgentFirstName: object
CoListAgentLastName: object
CoListOfficeName: object
ContractStatusChangeDate: object
CountyOrParish: object
CoveredSpaces: float64
DataMonth: int64
DaysOnMarket: int64
ElementarySchool: object
ElementarySchoolDistrict: float64
FireplaceYN: object
FireplacesTotal: float64
Flooring: object
GarageSpaces: float64
HighSchool: object
HighSchoolDistrict: object
Latitude: float64
Levels: object
ListAgentAOR: object
ListAgentEmail: object
ListAgentFirstName: object
ListAgentFullName: object
ListAgentLastName: object
ListOfficeName: object
ListPrice: float64
ListingContractDate: object
ListingId: object
ListingKey: int64
ListingKeyNumeric: int64
LivingArea: float64
Longitude: float64
LotSizeAcres: float64
LotSizeArea: float64
LotSizeDimensions: object
LotSizeSquareFeet: float64
MLSAreaMajor: object
MainLevelBedrooms: float64
MiddleOrJuniorSchool: object
MiddleOrJuniorSchoolDistrict: float64
MlsStatus: object
NewConstructionYN: object
OriginalListPrice: float64
ParkingTotal: float64
PoolPrivateYN: object
PostalCode: object
PropertySubType: object
PropertyType: object
PurchaseContractDate: object
StateOrProvince: object
Stories: float64
StreetNumberNumeric: float64
SubdivisionName: object
TaxAnnualAmount: float64
TaxYear: float64
UnparsedAddress: object
ViewYN: object
WaterfrontYN: object
YearBuilt: float64

In [315]:
housing_feature.isnull().sum().sort_values(ascending=False).head(20)

CoveredSpaces                   141997
BusinessType                    141997
ElementarySchoolDistrict        141997
MiddleOrJuniorSchoolDistrict    141997
TaxAnnualAmount                 141997
AboveGradeFinishedArea          141997
FireplacesTotal                 141997
TaxYear                         141997
WaterfrontYN                    141924
BelowGradeFinishedArea          140977
BasementYN                      138563
BuilderName                     135531
LotSizeDimensions               133007
BuildingAreaTotal               132503
CoBuyerAgentFirstName           128727
ElementarySchool                123493
MiddleOrJuniorSchool            123342
HighSchool                      117657
CoListAgentFirstName            108842
CoListAgentLastName             108737
dtype: int64

Columns being dropped

In [316]:
drop_cols = [
    "OriginalListPrice",
    "ListPrice",
    "ListingKeyNumeric",
    "ListingId",
    "ListAgentFirstName",
    "ListAgentLastName",
    "ListAgentFullName",
    "ListAgentEmail",
    "BuyerAgentFirstName",
    "BuyerAgentLastName",
    "BuyerAgentMlsId",
    "CoBuyerAgentFirstName",
    "CoListAgentFirstName",
    "CoListAgentLastName",
    "ListOfficeName",
    "BuyerOfficeName",
    "CoListOfficeName",
    "UnparsedAddress"]

#dropped more after seeing these columns had a great amount of missing values
drop_cols.extend([
    "TaxAnnualAmount",
    "AboveGradeFinishedArea",
    "FireplacesTotal",
    "CoveredSpaces",
    "TaxYear",
    "StreetNumberNumeric",
    "PurchaseContractDate"])

Numeric Columns that will be inputed with median

In [317]:
median_cols = [
    "LivingArea",
    "DaysOnMarket",
    "FireplacesTotal",
    "AboveGradeFinishedArea",
    "TaxAnnualAmount",
    "ParkingTotal",
    "LotSizeAcres",
    "YearBuilt",
    "BathroomsTotalInteger",
    "BuildingAreaTotal",
    "BedroomsTotal",
    "BelowGradeFinishedArea",
    "CoveredSpaces",
    "Stories",
    "LotSizeArea",
    "MainLevelBedrooms",
    "GarageSpaces",
    "AssociationFee",
    "Latitude",
    "Longitude",
    "LotSizeSquareFeet"]

Categorical columns that will be inputed with mode

In [318]:
mode_cols = [
    "BuyerAgentAOR",
    "ListAgentAOR",
    "AssociationFeeFrequency",
    "MLSAreaMajor",
    "CountyOrParish",
    "MlsStatus",
    "ElementarySchool",
    "ElementarySchoolDistrict",
    "BuilderName",
    "SubdivisionName",
    "BuyerOfficeAOR",
    "BusinessType",
    "StateOrProvince",
    "MiddleOrJuniorSchool",
    "MiddleOrJuniorSchoolDistrict",
    "HighSchool",
    "HighSchoolDistrict",
    "City",
    "PostalCode",
    "Levels",
    "LotSizeDimensions"]

Boolean

In [319]:
unknown_cols = [
    "ViewYN",
    "WaterfrontYN",
    "BasementYN",
    "PoolPrivateYN",
    "AttachedGarageYN",
    "FireplaceYN",
    "NewConstructionYN"]

Dropping columns and duplicates, and remove missing and null values from close price

In [320]:
housing_feature = housing_feature.drop(columns=drop_cols)
housing_feature = housing_feature.drop_duplicates(subset="ListingKey")
housing_feature = housing_feature.dropna(subset=["ClosePrice"])

Imputation using median and model and adding unknown to boolean columns

In [321]:
for col in median_cols:
    if col in housing_feature.columns:
        housing_feature[col] = housing_feature[col].fillna(housing_feature[col].median())

for col in mode_cols:
    if col in housing_feature.columns:
        # Check if mode returns an empty Series
        if not housing_feature[col].mode().empty:
            housing_feature[col] = housing_feature[col].fillna(housing_feature[col].mode()[0])
        else:
            # If mode fill with Unknown
            housing_feature[col] = housing_feature[col].fillna("Unknown")

for col in unknown_cols:
    if col in housing_feature.columns:
        housing_feature[col] = housing_feature[col].fillna("Unknown")

housing_feature["Flooring"] = housing_feature["Flooring"].fillna("Unknown")

In [322]:
missing = housing_feature.isnull().sum()
print("missing:\n",missing)

print("\nduplicates:")
dupes = housing_feature["ListingKey"].duplicated().sum()
print(dupes)

print(f"Rows kept: {len(housing_feature)/len(housing)*100:.2f}%")

housing_feature.isnull().sum().sort_values(ascending=False).head(20)

missing:
 BuyerAgentAOR                   0
ListAgentAOR                    0
Flooring                        0
ViewYN                          0
WaterfrontYN                    0
BasementYN                      0
PoolPrivateYN                   0
ListingKey                      0
CloseDate                       0
ClosePrice                      0
Latitude                        0
Longitude                       0
PropertyType                    0
LivingArea                      0
DaysOnMarket                    0
AssociationFeeFrequency         0
MLSAreaMajor                    0
CountyOrParish                  0
MlsStatus                       0
ElementarySchool                0
AttachedGarageYN                0
ParkingTotal                    0
BuilderName                     0
PropertySubType                 0
LotSizeAcres                    0
SubdivisionName                 0
BuyerOfficeAOR                  0
YearBuilt                       0
BathroomsTotalInteger           0
City                            0
BuildingAreaTotal               0
BedroomsTotal                   0
ContractStatusChangeDate        0
ElementarySchoolDistrict        0
ListingContractDate             0
BelowGradeFinishedArea          0
BusinessType                    0
StateOrProvince                 0
MiddleOrJuniorSchool            0
FireplaceYN                     0
Stories                         0
HighSchool                      0
Levels                          0
LotSizeDimensions               0
LotSizeArea                     0
MainLevelBedrooms               0
NewConstructionYN               0
GarageSpaces                    0
HighSchoolDistrict              0
PostalCode                      0
AssociationFee                  0
LotSizeSquareFeet               0
MiddleOrJuniorSchoolDistrict    0
DataMonth                       0
dtype: int64

duplicates:
0
Rows kept: 99.93%

BuyerAgentAOR              0
ListAgentAOR               0
Flooring                   0
ViewYN                     0
WaterfrontYN               0
BasementYN                 0
PoolPrivateYN              0
ListingKey                 0
CloseDate                  0
ClosePrice                 0
Latitude                   0
Longitude                  0
PropertyType               0
LivingArea                 0
DaysOnMarket               0
AssociationFeeFrequency    0
MLSAreaMajor               0
CountyOrParish             0
MlsStatus                  0
ElementarySchool           0
dtype: int64

In [323]:
comparison = pd.DataFrame({
    "Strategy": [
        "Original",
        "Drop all missing",
        "Median/Mode",
        "Feature-specific"],
    "Rows": [
        len(housing),
        len(housing_drop),
        len(housing_median),
        len(housing_feature)],
    "Columns": [
        housing.shape[1],
        housing_drop.shape[1],
        housing_median.shape[1],
        housing_feature.shape[1]],
    "Missing Values": [
        housing.isnull().sum().sum(),
        housing_drop.isnull().sum().sum(),
        housing_median.isnull().sum().sum(),
        housing_feature.isnull().sum().sum()]})

comparison["Rows Kept %"] = (comparison["Rows"] / len(housing) * 100).round(2)
comparison["Columns Kept %"] = (comparison["Columns"] / housing.shape[1] * 100).round(2)
comparison["Missing Values %"] = (comparison["Missing Values"] / housing.isnull().sum().sum() * 100).round(2)

print(comparison)

           Strategy    Rows  Columns  Missing Values  Rows Kept %  \
0          Original  141997       79         3289497       100.00
1  Drop all missing       0       79               0         0.00
2       Median/Mode  141892       79         1135136        99.93
3  Feature-specific  141892       54               0        99.93

   Columns Kept %  Missing Values %
0          100.00            100.00
1          100.00              0.00
2          100.00             34.51
3           68.35              0.00

Dowload clean dataset

In [324]:
housing_clean = housing_feature.copy()
housing_clean.to_csv("CRMLS_Preprocessed_FeatureSpecific.csv", index=False)

Convert all categorical features into numeric dummy variables and separate predictor variables from the target variable

In [325]:
categorical_cols = housing_feature.select_dtypes(include="object").columns

housing_encoded = pd.get_dummies(housing_feature,columns=categorical_cols,drop_first=True)

print(housing_encoded.shape)

(141892, 23923)

In [326]:
X = housing_encoded.drop(columns=["ClosePrice"])
y = housing_encoded["ClosePrice"]

Use the most recent month as the test set and the res as the training set

In [327]:
#time base train/test split
latest_month = housing_encoded["DataMonth"].max()

train = housing_encoded[housing_encoded["DataMonth"] < latest_month]
test  = housing_encoded[housing_encoded["DataMonth"] == latest_month]

X_train = train.drop(columns=["ClosePrice"])
y_train = train["ClosePrice"]

X_test = test.drop(columns=["ClosePrice"])
y_test = test["ClosePrice"]

# Remove DataMonth after splitting since it is no longer needed as a predictor
X_train = X_train.drop(columns=["DataMonth"])
X_test = X_test.drop(columns=["DataMonth"])

Standardize numerical features so they are on the same scale and fitted the scaler using only the training data to avoid data leakage and then did the same transformation to the test data.

In [328]:
from sklearn.preprocessing import StandardScaler

numeric_features = X_train.select_dtypes(include="number").columns

scaler = StandardScaler()

X_train[numeric_features] = scaler.fit_transform(X_train[numeric_features])
X_test[numeric_features] = scaler.transform(X_test[numeric_features])